// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: alliance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录
type CsAccountLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName string `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
}

func (x *CsAccountLogin) Reset() {
	*x = CsAccountLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAccountLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAccountLogin) ProtoMessage() {}

func (x *CsAccountLogin) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAccountLogin.ProtoReflect.Descriptor instead.
func (*CsAccountLogin) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{0}
}

func (x *CsAccountLogin) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type ScAccountLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   int64  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
}

func (x *ScAccountLogin) Reset() {
	*x = ScAccountLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAccountLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAccountLogin) ProtoMessage() {}

func (x *ScAccountLogin) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAccountLogin.ProtoReflect.Descriptor instead.
func (*ScAccountLogin) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{1}
}

func (x *ScAccountLogin) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ScAccountLogin) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

// 登出
type CsAccountLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsAccountLogout) Reset() {
	*x = CsAccountLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAccountLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAccountLogout) ProtoMessage() {}

func (x *CsAccountLogout) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAccountLogout.ProtoReflect.Descriptor instead.
func (*CsAccountLogout) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{2}
}

type ScAccountLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScAccountLogout) Reset() {
	*x = ScAccountLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAccountLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAccountLogout) ProtoMessage() {}

func (x *ScAccountLogout) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAccountLogout.ProtoReflect.Descriptor instead.
func (*ScAccountLogout) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{3}
}

// 加入公会情况
type CsAllianceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsAllianceInfo) Reset() {
	*x = CsAllianceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceInfo) ProtoMessage() {}

func (x *CsAllianceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceInfo.ProtoReflect.Descriptor instead.
func (*CsAllianceInfo) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{4}
}

type ScAllianceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       int64    `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	AllianceName string   `protobuf:"bytes,2,opt,name=AllianceName,proto3" json:"AllianceName,omitempty"`
	Members      []string `protobuf:"bytes,3,rep,name=Members,proto3" json:"Members,omitempty"`
}

func (x *ScAllianceInfo) Reset() {
	*x = ScAllianceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceInfo) ProtoMessage() {}

func (x *ScAllianceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceInfo.ProtoReflect.Descriptor instead.
func (*ScAllianceInfo) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{5}
}

func (x *ScAllianceInfo) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ScAllianceInfo) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

func (x *ScAllianceInfo) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

// 创建公会
type CsAllianceCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *CsAllianceCreate) Reset() {
	*x = CsAllianceCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceCreate) ProtoMessage() {}

func (x *CsAllianceCreate) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceCreate.ProtoReflect.Descriptor instead.
func (*CsAllianceCreate) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{6}
}

func (x *CsAllianceCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ScAllianceCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ScAllianceCreate) Reset() {
	*x = ScAllianceCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceCreate) ProtoMessage() {}

func (x *ScAllianceCreate) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceCreate.ProtoReflect.Descriptor instead.
func (*ScAllianceCreate) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{7}
}

func (x *ScAllianceCreate) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ScAllianceCreate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 公会列表
type CsAllianceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsAllianceList) Reset() {
	*x = CsAllianceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceList) ProtoMessage() {}

func (x *CsAllianceList) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceList.ProtoReflect.Descriptor instead.
func (*CsAllianceList) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{8}
}

type ScAllianceList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceList []string `protobuf:"bytes,1,rep,name=AllianceList,proto3" json:"AllianceList,omitempty"`
}

func (x *ScAllianceList) Reset() {
	*x = ScAllianceList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceList) ProtoMessage() {}

func (x *ScAllianceList) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceList.ProtoReflect.Descriptor instead.
func (*ScAllianceList) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{9}
}

func (x *ScAllianceList) GetAllianceList() []string {
	if x != nil {
		return x.AllianceList
	}
	return nil
}

// 加入公会
type CsAllianceJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllianceName string `protobuf:"bytes,1,opt,name=AllianceName,proto3" json:"AllianceName,omitempty"`
}

func (x *CsAllianceJoin) Reset() {
	*x = CsAllianceJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceJoin) ProtoMessage() {}

func (x *CsAllianceJoin) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceJoin.ProtoReflect.Descriptor instead.
func (*CsAllianceJoin) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{10}
}

func (x *CsAllianceJoin) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

type ScAllianceJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       int64  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	AllianceName string `protobuf:"bytes,2,opt,name=AllianceName,proto3" json:"AllianceName,omitempty"`
}

func (x *ScAllianceJoin) Reset() {
	*x = ScAllianceJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceJoin) ProtoMessage() {}

func (x *ScAllianceJoin) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceJoin.ProtoReflect.Descriptor instead.
func (*ScAllianceJoin) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{11}
}

func (x *ScAllianceJoin) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ScAllianceJoin) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

// 解散公会
type CsAllianceDismiss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsAllianceDismiss) Reset() {
	*x = CsAllianceDismiss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceDismiss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceDismiss) ProtoMessage() {}

func (x *CsAllianceDismiss) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceDismiss.ProtoReflect.Descriptor instead.
func (*CsAllianceDismiss) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{12}
}

type ScAllianceDismiss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       int64  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	AllianceName string `protobuf:"bytes,2,opt,name=AllianceName,proto3" json:"AllianceName,omitempty"`
}

func (x *ScAllianceDismiss) Reset() {
	*x = ScAllianceDismiss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceDismiss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceDismiss) ProtoMessage() {}

func (x *ScAllianceDismiss) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceDismiss.ProtoReflect.Descriptor instead.
func (*ScAllianceDismiss) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{13}
}

func (x *ScAllianceDismiss) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ScAllianceDismiss) GetAllianceName() string {
	if x != nil {
		return x.AllianceName
	}
	return ""
}

// 公会扩容
type CsAllianceIncreaseCapacity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsAllianceIncreaseCapacity) Reset() {
	*x = CsAllianceIncreaseCapacity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceIncreaseCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceIncreaseCapacity) ProtoMessage() {}

func (x *CsAllianceIncreaseCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceIncreaseCapacity.ProtoReflect.Descriptor instead.
func (*CsAllianceIncreaseCapacity) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{14}
}

type ScAllianceIncreaseCapacity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   int64 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Capacity int64 `protobuf:"varint,2,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
}

func (x *ScAllianceIncreaseCapacity) Reset() {
	*x = ScAllianceIncreaseCapacity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceIncreaseCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceIncreaseCapacity) ProtoMessage() {}

func (x *ScAllianceIncreaseCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceIncreaseCapacity.ProtoReflect.Descriptor instead.
func (*ScAllianceIncreaseCapacity) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{15}
}

func (x *ScAllianceIncreaseCapacity) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ScAllianceIncreaseCapacity) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

// 提交物品到仓库
type CsAllianceStoreItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`         // 物品Id
	Number int32 `protobuf:"varint,2,opt,name=Number,proto3" json:"Number,omitempty"` // 物品数量
	Index  int32 `protobuf:"varint,3,opt,name=Index,proto3" json:"Index,omitempty"`   // 物品格子序号
}

func (x *CsAllianceStoreItem) Reset() {
	*x = CsAllianceStoreItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceStoreItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceStoreItem) ProtoMessage() {}

func (x *CsAllianceStoreItem) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceStoreItem.ProtoReflect.Descriptor instead.
func (*CsAllianceStoreItem) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{16}
}

func (x *CsAllianceStoreItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CsAllianceStoreItem) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CsAllianceStoreItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ScAllianceStoreItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ScAllianceStoreItem) Reset() {
	*x = ScAllianceStoreItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceStoreItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceStoreItem) ProtoMessage() {}

func (x *ScAllianceStoreItem) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceStoreItem.ProtoReflect.Descriptor instead.
func (*ScAllianceStoreItem) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{17}
}

func (x *ScAllianceStoreItem) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 会长消耗某格仓库
type CsAllianceDestroyItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
}

func (x *CsAllianceDestroyItem) Reset() {
	*x = CsAllianceDestroyItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceDestroyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceDestroyItem) ProtoMessage() {}

func (x *CsAllianceDestroyItem) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceDestroyItem.ProtoReflect.Descriptor instead.
func (*CsAllianceDestroyItem) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{18}
}

func (x *CsAllianceDestroyItem) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ScAllianceDestroyItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ScAllianceDestroyItem) Reset() {
	*x = ScAllianceDestroyItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceDestroyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceDestroyItem) ProtoMessage() {}

func (x *ScAllianceDestroyItem) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceDestroyItem.ProtoReflect.Descriptor instead.
func (*ScAllianceDestroyItem) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{19}
}

func (x *ScAllianceDestroyItem) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 仓库整理
type CsAllianceClearup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CsAllianceClearup) Reset() {
	*x = CsAllianceClearup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CsAllianceClearup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsAllianceClearup) ProtoMessage() {}

func (x *CsAllianceClearup) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsAllianceClearup.ProtoReflect.Descriptor instead.
func (*CsAllianceClearup) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{20}
}

type ScAllianceClearup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *ScAllianceClearup) Reset() {
	*x = ScAllianceClearup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScAllianceClearup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScAllianceClearup) ProtoMessage() {}

func (x *ScAllianceClearup) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScAllianceClearup.ProtoReflect.Descriptor instead.
func (*ScAllianceClearup) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{21}
}

func (x *ScAllianceClearup) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 心跳检测
type ClientHeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientHeartBeat) Reset() {
	*x = ClientHeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alliance_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHeartBeat) ProtoMessage() {}

func (x *ClientHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_alliance_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHeartBeat.ProtoReflect.Descriptor instead.
func (*ClientHeartBeat) Descriptor() ([]byte, []int) {
	return file_alliance_proto_rawDescGZIP(), []int{22}
}

var File_alliance_proto protoreflect.FileDescriptor

var file_alliance_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x2c, 0x0a, 0x0e, 0x43, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x44, 0x0a, 0x0e, 0x53, 0x63, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x73, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x53,
	0x63, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x22, 0x10,
	0x0a, 0x0e, 0x43, 0x73, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x66, 0x0a, 0x0e, 0x53, 0x63, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x73, 0x41, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x3e, 0x0a, 0x10, 0x53, 0x63, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x10, 0x0a, 0x0e, 0x43, 0x73, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x34, 0x0a, 0x0e, 0x53, 0x63, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x0e, 0x43, 0x73, 0x41, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x6c,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4c,
	0x0a, 0x0e, 0x53, 0x63, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4a, 0x6f, 0x69, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x13, 0x0a, 0x11,
	0x43, 0x73, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x69, 0x73, 0x6d, 0x69, 0x73,
	0x73, 0x22, 0x4f, 0x0a, 0x11, 0x53, 0x63, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x44,
	0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22,
	0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x73, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x50, 0x0a, 0x1a, 0x53, 0x63, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e,
	0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69,
	0x74, 0x79, 0x22, 0x53, 0x0a, 0x13, 0x43, 0x73, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2d, 0x0a, 0x13, 0x53, 0x63, 0x41, 0x6c, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2d, 0x0a, 0x15, 0x43, 0x73, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2f, 0x0a, 0x15, 0x53, 0x63, 0x41, 0x6c, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x43, 0x73, 0x41, 0x6c, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x75, 0x70, 0x22, 0x2b, 0x0a, 0x11, 0x53,
	0x63, 0x41, 0x6c, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x75, 0x70,
	0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x70,
	0x62, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alliance_proto_rawDescOnce sync.Once
	file_alliance_proto_rawDescData = file_alliance_proto_rawDesc
)

func file_alliance_proto_rawDescGZIP() []byte {
	file_alliance_proto_rawDescOnce.Do(func() {
		file_alliance_proto_rawDescData = protoimpl.X.CompressGZIP(file_alliance_proto_rawDescData)
	})
	return file_alliance_proto_rawDescData
}

var file_alliance_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_alliance_proto_goTypes = []interface{}{
	(*CsAccountLogin)(nil),             // 0: pb.CsAccountLogin
	(*ScAccountLogin)(nil),             // 1: pb.ScAccountLogin
	(*CsAccountLogout)(nil),            // 2: pb.CsAccountLogout
	(*ScAccountLogout)(nil),            // 3: pb.ScAccountLogout
	(*CsAllianceInfo)(nil),             // 4: pb.CsAllianceInfo
	(*ScAllianceInfo)(nil),             // 5: pb.ScAllianceInfo
	(*CsAllianceCreate)(nil),           // 6: pb.CsAllianceCreate
	(*ScAllianceCreate)(nil),           // 7: pb.ScAllianceCreate
	(*CsAllianceList)(nil),             // 8: pb.CsAllianceList
	(*ScAllianceList)(nil),             // 9: pb.ScAllianceList
	(*CsAllianceJoin)(nil),             // 10: pb.CsAllianceJoin
	(*ScAllianceJoin)(nil),             // 11: pb.ScAllianceJoin
	(*CsAllianceDismiss)(nil),          // 12: pb.CsAllianceDismiss
	(*ScAllianceDismiss)(nil),          // 13: pb.ScAllianceDismiss
	(*CsAllianceIncreaseCapacity)(nil), // 14: pb.CsAllianceIncreaseCapacity
	(*ScAllianceIncreaseCapacity)(nil), // 15: pb.ScAllianceIncreaseCapacity
	(*CsAllianceStoreItem)(nil),        // 16: pb.CsAllianceStoreItem
	(*ScAllianceStoreItem)(nil),        // 17: pb.ScAllianceStoreItem
	(*CsAllianceDestroyItem)(nil),      // 18: pb.CsAllianceDestroyItem
	(*ScAllianceDestroyItem)(nil),      // 19: pb.ScAllianceDestroyItem
	(*CsAllianceClearup)(nil),          // 20: pb.CsAllianceClearup
	(*ScAllianceClearup)(nil),          // 21: pb.ScAllianceClearup
	(*ClientHeartBeat)(nil),            // 22: pb.ClientHeartBeat
}
var file_alliance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_alliance_proto_init() }
func file_alliance_proto_init() {
	if File_alliance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alliance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAccountLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAccountLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAccountLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAccountLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceDismiss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceDismiss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceIncreaseCapacity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceIncreaseCapacity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceStoreItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceStoreItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceDestroyItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceDestroyItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CsAllianceClearup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScAllianceClearup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alliance_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientHeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alliance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alliance_proto_goTypes,
		DependencyIndexes: file_alliance_proto_depIdxs,
		MessageInfos:      file_alliance_proto_msgTypes,
	}.Build()
	File_alliance_proto = out.File
	file_alliance_proto_rawDesc = nil
	file_alliance_proto_goTypes = nil
	file_alliance_proto_depIdxs = nil
}
